### ISSUE TITLE
Documentation is needed

### ISSUE THREAD

**Issue by adriacabeza** [GalBrandwine/HalloPy#2]
Hi, I think your project is really cool but it really needs a proper documentation about all the available hand gestures.

**Comment by GalBrandwine** [comment]
Hey Lord Santana.
It has been a wile since I have worked on that project.

so i think the fastest way for explaining is by a video:

https://youtu.be/NSwKCzxFBv4

hope it helps. Gal

‫בתאריך שבת, 15 ביוני 2019 ב-13:08 מאת ‪lord_santanna‬‏ <‪
notifications@github.com‬‏>:‬
