### ISSUE TITLE
No module named 'hallopy'

### ISSUE THREAD

**Issue by Jacobprojects** [GalBrandwine/HalloPy#3]
hello GalBrandwine I'm trying to use the code but when I run ~$ python hallo.py I got this error. I hope u can help me. 

Traceback (most recent call last):
  File "hallo.py", line 3, in <module>
    from hallopy.controller import Controller
ModuleNotFoundError: No module named 'hallopy'

**Comment by galbra92** [comment]
Hey! thanks for using my project :)

When receiving this kind of messages it is usually because of package location on your pc. make sue that you start your python interpreter from HalloPy folder.

hope it helps, Gal

**Comment by Jacobprojects** [comment]
Thanks to you for share us you project.

U can be more specific about package ? 

<img width="570" alt="Screen Shot 2019-09-25 at 1 25 30 PM" src="https://user-images.githubusercontent.com/54909362/65632885-faa9d280-df97-11e9-831c-0ca745ee7f0b.png">

when I run the code that's the error. Thanks for you attention.

**Comment by GalBrandwine** [comment]
Hey, 

when python doesn't find a package in its PYTHONPATH it raise this MODULENOTFOUND error

try running python:

```
import sys
print(sys.executable)
```

Actually it is not an issue in my repository, but a python path configuration problem.
Hope it all work out..
im closing this issue, and if you need more help with this problem, im available on my mail.

cheers, Gal

**Comment by raclab** [comment]
why don't you give exact solution for the problem asked by two person? I have the same problem.

**Comment by raclab** [comment]
~/Documents/HalloPy/hallopy$ python hallo.py 
Traceback (most recent call last):
  File "hallo.py", line 3, in <module>
    from hallopy.controller import Controller
ModuleNotFoundError: No module named 'hallopy'


can you explain why we get this error?

**Comment by GalBrandwine** [comment]
Hey!
Fixed it, try now?

Gal
