### ISSUE TITLE
I can't see any video stream nor any gui, help.

### ISSUE THREAD

**Issue by RahilRehan** [GalBrandwine/HalloPy#4]
![20200206_104232](https://user-images.githubusercontent.com/29269254/73907752-80864480-48cd-11ea-9539-3294c7fb4086.jpg)
Two boxes are present but no video stream.

**Comment by GalBrandwine** [comment]
Hey!
Can you read any frames from camera?

**Comment by RahilRehan** [comment]
> Hey!
> Can you read any frames from camera?

How do I check that?

**Comment by GalBrandwine** [comment]
First try to see if you can read frames properly from your camera:
```python
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
```

For more tutorials  - [openCV](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html)

Hope it helps, Gal

**Comment by GalBrandwine** [comment]
Hey @RahilRehan ,
Have you managed?

**Comment by RahilRehan** [comment]
Oh yes, thanks for your help.
I don't exactly remeber what I did, but it worked out in the end.😅

**Comment by GalBrandwine** [comment]
K, closing

**Comment by GalBrandwine** [comment]
K, closing
